resources:
- name: potter 
  type: git
  source:
    uri: http://github.com/cjlee37/concourse-pipeline.git
    branch: master

jobs:
- name: hello-world
  plan:
  - get: potter
    trigger: true
  - get: my-other-resource
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ayu1990/test}

      run:
        path: echo
        args: ["Hello, world!"]
