resources:
- name: potter 
  type: git
  source:
    uri: http://github.com/cjlee37/concourse-pipeline.git
    branch: master
- name: my-other-resource
  type: git
  source:
    uri: https://github.com/cjlee37/concourse-pipeline.git
    branch: master

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.6"}

jobs:
- name: hello-world
  plan:
  - get: potter
    trigger: true
  - get: my-other-resource
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
